name: CI - Validation

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]
#/usr/local/aria2/bin/
jobs:
  build:
    name: Validate
    runs-on: macOS-15
    if: github.repository_owner == 'hackdoc'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Validate
        run: |
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install --upgrade pip
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install -r requirements.txt
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install packaging
          rm -rf Univ*
          aria2c -x 16 "https://github.com/hackdoc/PatcherSupportPkg/releases/download/1.9.9pre2/Universal-Binaries.dmg"
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 OCLP-R-GUI.command --validate
